In [26]:
#in jupyter !pip  install numpy!
#in cmd pip install numpy

In [50]:
import numpy as np

print(np.__version__)
   

2.4.6


In [51]:
 #list in array
lst =[2,3,4,545,23,32,43,5,210]
print(lst)
print(type(lst))
print("Converting list into array ")
arr=np.array(lst)
print("This is a array :-",arr)
print(type(arr))

[2, 3, 4, 545, 23, 32, 43, 5, 210]
<class 'list'>
Converting list into array 
This is a array :- [  2   3   4 545  23  32  43   5 210]
<class 'numpy.ndarray'>


In [52]:
arr = np.array([3,4,5,6,7])
print(arr)
print(type(arr))

[3 4 5 6 7]
<class 'numpy.ndarray'>


In [53]:
lst =list(range(1,20))
print(lst)
print(type(lst))
arr=np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [54]:
arr =np.array(list(range(1,20)))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [55]:
arr = np.array(21)
print(arr)

21


In [56]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [57]:

arr = np.zeros((3, 4)) # row =3 column =4

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
arr =np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [59]:
arr = np.ones((3,5)) # row = 3 column =5
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
arr = np.arange(12) # same like range function 
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print(arr1)
print(arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int64
12
(12,)
1


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)  # convert 1 D to 2 D array 

print(new_arr) 

[[1 2 3]
 [4 5 6]]


In [63]:
arr = np.arange(60)
arr1 =arr.reshape(12,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [64]:
# 3 incidingg
arr[0], arr[1] , arr[0:4]


(np.int64(0), np.int64(1), array([0, 1, 2, 3]))

In [65]:
#slicinggggggg
arr[0:5]

array([0, 1, 2, 3, 4])

In [66]:
arr[0:51:3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [67]:
arr[11:4]

array([], dtype=int64)

In [68]:
arr[0:50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
arr[0:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [70]:
print(arr1[4:6,2:4])

[[22 23]
 [27 28]]


In [71]:
print(arr1[4:6])

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [73]:
arr1[4:6,2:4]

array([[22, 23],
       [27, 28]])

In [74]:
arr=np.array([1,2,3,4,65,4])
np.min(arr)
np.argmin(arr)

np.int64(0)

In [77]:
np.argmax(arr)

np.int64(4)

In [78]:

np.sort(arr)

array([ 1,  2,  3,  4,  4, 65])

In [79]:
np.argsort(arr)

array([0, 1, 2, 3, 5, 4])

In [80]:
arr=np.array([[1,2]
    ,[2,3]])
print(arr)
print(type(arr))

[[1 2]
 [2 3]]
<class 'numpy.ndarray'>


In [82]:
print(arr.flatten())
print(np.where(arr==2))

[1 2 2 3]
(array([0, 1]), array([1, 0]))


In [84]:
arr=np.array([10,20,30,54])
print(np.where(arr==20))

(array([1]),)


In [85]:
arr=np.zeros(2)
print(arr)

[0. 0.]


In [87]:
arr=np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [93]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [94]:
np.arange(1,10,6)

array([1, 7])